Moongeul/Backend

- build.gradle
- src/main/java/com/core/book/api/member/controller/MemberController.java
- src/main/java/com/core/book/api/member/entity/Member.java
- src/main/java/com/core/book/api/member/entity/Role.java
- src/main/java/com/core/book/api/member/jwt/filter/JwtAuthenticationProcessingFilter.java
- src/main/java/com/core/book/api/member/jwt/service/JwtService.java
- src/main/java/com/core/book/api/member/jwt/util/PasswordUtil.java
- src/main/java/com/core/book/api/member/oauth2/CustomOAuth2User.java
- src/main/java/com/core/book/api/member/oauth2/OAuthAttributes.java
- src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginFailureHandler.java
- src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java
- src/main/java/com/core/book/api/member/oauth2/userinfo/KakaoOAuth2UserInfo.java
- src/main/java/com/core/book/api/member/oauth2/userinfo/OAuth2UserInfo.java
- src/main/java/com/core/book/api/member/repository/MemberRepository.java
- src/main/java/com/core/book/api/member/service/MemberService.java
- src/main/java/com/core/book/common/config/SecurityConfig.java
- src/main/java/com/core/book/common/config/jwt/JwtConfig.java
- src/main/java/com/core/book/common/config/oauth2/OAuth2Config.java
- src/main/java/com/core/book/common/exception/NotFoundException.java
- src/main/java/com/core/book/common/response/ErrorStatus.java
- src/main/java/com/core/book/common/response/SuccessStatus.java
- close #11 
카카오 OAuth2.0 회원가입/로그인 기능을 구현했습니다.
- JWT 토큰 사용
- 카카오 OAuth2 기능 엔드포인트 : {URL}/oauth2/authorization/kakao
- 임시로 처음사용자(role = guest)일 경우 google.com, 기존사용자(role = User)일 경우 naver.com 으로 리다이렉트 수행하였습니다.
- 처음사용자일 경우 AccessToken 만 발급되고, 기존사용자일경우 AccessToken, RefreshToken이 발급됩니다.
- AccessToken 인증 헤더는 Authorization / RefreshToken 인증 헤더는 Authorization-refresh 입니다.
- AccessToken 재발급 로직은 엔드포인트에 Authorization, Authorization-refresh 각각 헤더에 토큰이 있을경우 재발급이 수행됩니다.
> [FEAT] 카카오 OAuth2.0 구현

- build.gradle
- src/main/java/com/core/book/api/member/controller/MemberController.java
- src/main/java/com/core/book/api/member/dto/UserTagRequestDTO.java
- src/main/java/com/core/book/api/member/entity/InfoOpen.java
- src/main/java/com/core/book/api/member/entity/Member.java
- src/main/java/com/core/book/api/member/entity/Role.java
- src/main/java/com/core/book/api/member/entity/UserTag.java
- src/main/java/com/core/book/api/member/jwt/filter/JwtAuthenticationProcessingFilter.java
- src/main/java/com/core/book/api/member/jwt/service/JwtService.java
- src/main/java/com/core/book/api/member/jwt/util/PasswordUtil.java
- src/main/java/com/core/book/api/member/oauth2/CustomOAuth2User.java
- src/main/java/com/core/book/api/member/oauth2/OAuthAttributes.java
- src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginFailureHandler.java
- src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java
- src/main/java/com/core/book/api/member/oauth2/userinfo/KakaoOAuth2UserInfo.java
- src/main/java/com/core/book/api/member/oauth2/userinfo/OAuth2UserInfo.java
- src/main/java/com/core/book/api/member/repository/InfoOpenRepository.java
- src/main/java/com/core/book/api/member/repository/MemberRepository.java
- src/main/java/com/core/book/api/member/repository/UserTagRepository.java
- src/main/java/com/core/book/api/member/service/MemberService.java
- src/main/java/com/core/book/common/config/SecurityConfig.java
- src/main/java/com/core/book/common/config/jwt/JwtConfig.java
- src/main/java/com/core/book/common/config/oauth2/OAuth2Config.java
- src/main/java/com/core/book/common/config/swagger/SwaggerConfig.java
- src/main/java/com/core/book/common/entity/BaseTimeEntity.java
- src/main/java/com/core/book/common/exception/BadRequestException.java
- src/main/java/com/core/book/common/exception/NotFoundException.java
- src/main/java/com/core/book/common/response/ApiResponse.java
- src/main/java/com/core/book/common/response/ErrorStatus.java
- src/main/java/com/core/book/common/response/SuccessStatus.java
- close #18 
- 처음 접속한 사용자 추가 설정(마케팅 정보 동의 여부, 선호하는 책 취향 태그, 정보 공개 여부) 등록 기능을 구현하였습니다.
- 태그 등록 엔드포인트 :  POST {URL}/api/v1/member/initial-tags
[ 태그 등록 POST Request 형식]
{
"tag1" : "",
"tag2" : "",
"tag3" : "",
"tag4" : "",
"tag5" : ""
}
- 마케팅 정보 동의 엔드포인트 : GET {URL}/api/v1/member/initial-marketing?approve={ok/no}
- Member 엔티티 내 Builder 패턴으로 코드 리팩토링 하였습니다.
- accessToken, refreshToken 전달 방식을 헤더에서 Cookie 방식으로 변경하였습니다.
- ApiResponse 클래스 사용시 발생한 제너릭 경고를 해결하였습니다.
- 사용자의 Role이 User로 승격될 때 accessToken, refreshToken 토큰이 발급되도록 코드 수정하였습니다.
- 처음 회원가입한 사용자의 정보공개 초기값이 TRUE로 되도록 설정하였습니다.
- 정보수정시 BaseTimeEntity 내 createAt가 null로 초기화 되는 문제를 해결하였습니다.
> [FEAT] 처음 접속한 사용자 추가 설정(마케팅 정보 동의 여부, 선호하는 책 취향 태그, 정보 공개 여부) 등록 기능 구현

- src/main/java/com/core/book/api/book/controller/BookController.java
- src/main/java/com/core/book/api/book/service/BookService.java
- src/main/java/com/core/book/api/member/controller/MemberController.java
- src/main/java/com/core/book/common/response/ApiResponse.java
- src/main/java/com/core/book/common/response/ErrorStatus.java
- close #34 
- 도서 API 에서 발생할 수 있는 두 가지 예외 처리 기능을 추가하였습니다. 
- (1) 검색어가 없는 경우 400 응답 (2) 검색 결과가 없는 경우 404 응답
- ApiResponse 코드 내 success(_only) 메서드에 ResponseEntity 를 씌워 해당 코드에서 http 응답을 한 번에 보낼 수 있게 수정하였습니다.
> [FIX] 도서 API 예외 처리 추가

- build.gradle
- src/main/java/com/core/book/api/member/controller/MemberController.java
- src/main/java/com/core/book/api/member/dto/InfoOpenRequestDTO.java
- src/main/java/com/core/book/api/member/dto/UserInfoResponseDTO.java
- src/main/java/com/core/book/api/member/entity/InfoOpen.java
- src/main/java/com/core/book/api/member/entity/Member.java
- src/main/java/com/core/book/api/member/jwt/service/JwtService.java
- src/main/java/com/core/book/api/member/repository/InfoOpenRepository.java
- src/main/java/com/core/book/api/member/repository/MemberRepository.java
- src/main/java/com/core/book/api/member/service/MemberService.java
- src/main/java/com/core/book/api/member/service/S3Service.java
- src/main/java/com/core/book/common/config/aws/S3Config.java
- src/main/java/com/core/book/common/exception/InternalServerException.java
- src/main/java/com/core/book/common/response/ErrorStatus.java
- src/main/java/com/core/book/common/response/SuccessStatus.java
- close #31 
- 회원 정보 수정(프로필사진, 닉네임, 정보공개, 탈퇴) 기능 및 사용자의 정보를 조회 할 수 있는 기능을 구현하였습니다.
- Member 와 UserTag 및 UserInfo 를 순환참조 오류를 해결하기 위해 양방향에서 단방향으로 수정하였습니다.
- Build.grade 에서 의존성 모두 최신버전으로 업데이트 하였습니다.
> [FEAT] 회원 정보 수정(프로필사진, 닉네임, 정보공개, 탈퇴) 및 조회 기능 구현

- build.gradle
- src/main/java/com/core/book/api/member/controller/MemberController.java
- src/main/java/com/core/book/api/member/dto/FollowRequestDTO.java
- src/main/java/com/core/book/api/member/dto/FollowedUserDTO.java
- src/main/java/com/core/book/api/member/dto/InfoOpenRequestDTO.java
- src/main/java/com/core/book/api/member/dto/UserInfoResponseDTO.java
- src/main/java/com/core/book/api/member/entity/Follow.java
- src/main/java/com/core/book/api/member/entity/InfoOpen.java
- src/main/java/com/core/book/api/member/entity/Member.java
- src/main/java/com/core/book/api/member/jwt/service/JwtService.java
- src/main/java/com/core/book/api/member/repository/FollowRepository.java
- src/main/java/com/core/book/api/member/repository/InfoOpenRepository.java
- src/main/java/com/core/book/api/member/repository/MemberRepository.java
- src/main/java/com/core/book/api/member/service/MemberService.java
- src/main/java/com/core/book/api/member/service/S3Service.java
- src/main/java/com/core/book/common/config/aws/S3Config.java
- src/main/java/com/core/book/common/exception/InternalServerException.java
- src/main/java/com/core/book/common/response/ErrorStatus.java
- src/main/java/com/core/book/common/response/SuccessStatus.java
- close #42 
- 이미지 저장 로직 개선을 위한 자체 CDN 캐시 서버 구축 및 연동하였습니다.
CDN 캐시 서버란?)
콘텐츠 전송 네트워크(Content Delivery Network, CDN)의 일부로, 사용자가 요청한 콘텐츠를 더 빠르게 제공하기 위해 웹 콘텐츠(예: 이미지, 비디오, 스타일시트 등)를 가까운 서버에 임시로 저장해 두는 서버를 말한다.
CDN 캐시 서버의 주요 역할은 다음과 같다:
- 속도 향상: 사용자가 요청한 콘텐츠를 물리적으로 더 가까운 위치에서 제공함으로써, 콘텐츠 전송 속도를 크게 향상시킨다. 예를 들어, 사용자가 한국에 있고 서버가 미국에 있을 때, CDN 캐시 서버가 한국에 위치해 있으면 사용자는 미국이 아닌 한국의 서버에서 콘텐츠를 받아 더 빠르게 이용할 수 있다.
- 서버 부하 감소: 원본 서버(S3 버킷 등)에 대한 직접적인 요청을 줄여준다. 콘텐츠가 CDN 캐시 서버에 저장되면, 동일한 콘텐츠에 대한 추가 요청은 원본 서버가 아닌 캐시 서버에서 처리되기 때문에 원본 서버의 부하를 줄인다.
- 비용 절감: S3 버킷과 같은 원본 서버에 대한 요청을 줄여 데이터 전송 비용을 절감할 수 있다. 원본 서버에 한 번 요청된 콘텐츠가 캐시 서버에 저장되고, 이후의 요청은 캐시 서버에서 처리되기 때문에 S3 등의 클라우드 서비스 사용 비용을 줄인다.
- 고가용성: 원본 서버에 문제가 생기더라도 캐시 서버에 저장된 콘텐츠는 계속해서 제공될 수 있기 때문에 서비스의 가용성을 높인다.
CDN 캐시 서버를 적용한 이유)
캐시 서버를 적용하기 전에는 이미지 URL을 호출할 때마다 …
> [FIX] 이미지 저장 로직 개선을 위한 CDN 서버 구축 및 연동 

- src/main/java/com/core/book/api/book/controller/BookController.java
- src/main/java/com/core/book/api/book/dto/BookDto.java
- src/main/java/com/core/book/api/book/entity/Book.java
- src/main/java/com/core/book/api/book/entity/BookTag.java
- src/main/java/com/core/book/api/book/service/BookService.java
- src/main/java/com/core/book/api/member/controller/MemberController.java
- src/main/java/com/core/book/common/response/ApiResponse.java
- src/main/java/com/core/book/common/response/ErrorStatus.java
- close #41 
- 도서 검색 결과 페이징 처리 기능을 구현했습니다.
- 파라미터의 page, size 값으로 페이징 처리를 구현합니다. (page: 페이지 번호, size: 한 번에 표시할 검색 결과 개수)
- 각 파라미터 기본값 => page: 1, size: 10
- 응답 response에 '도서정보/page/size/totalSize(총 검색 결과 개수)' 를 반환합니다.
> [FEAT] 도서 검색 결과 페이징 처리 기능 구현

- src/main/java/com/core/book/api/member/controller/MemberController.java
- src/main/java/com/core/book/api/member/dto/OtherUserInfoResponseDTO.java
- src/main/java/com/core/book/api/member/service/MemberService.java
- src/main/java/com/core/book/common/exception/UnauthorizedException.java
- src/main/java/com/core/book/common/response/ErrorStatus.java
- close #46
- 프로필 이미지 확장자(jpg, jpeg, png, bmp, webp) 만 올릴 수 있도록 필터링 추가하였습니다.
> [FIX] 프로필 이미지 확장자 필터링 추가

- src/main/java/com/core/book/api/member/controller/MemberController.java
- src/main/java/com/core/book/api/member/dto/InfoOpenRequestDTO.java
- src/main/java/com/core/book/api/member/dto/UserInfoResponseDTO.java
- src/main/java/com/core/book/api/member/entity/InfoOpen.java
- src/main/java/com/core/book/api/member/service/MemberService.java
- src/main/java/com/core/book/common/config/swagger/SwaggerConfig.java
- src/main/java/com/core/book/common/response/SuccessStatus.java
- close #70
- 기존 닉네임 변경 API에서 닉네임 사용 가능 체크 기능을 분리하여 하나의 API로 따로 구현였습니다.
> [FIX] 닉네임 사용가능 체크 기능 분리

- src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
- src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
- src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfResponseDTO.java
- src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
- close #88 
- read 책장의 전체 책 개수 데이터를 추가하였습니다.
- wish 책장 전체 조회 API 반환 데이터를 Map 에서 DTO 로 변경하였습니다.
- return type이 Map 으로 정의될 경우 Swagger 에 표시되는 Response 정보가 정상적으로 구성되지 않고, "additionalProp1": "string" 형식으로 구성되는 이슈를 해결하였습니다.
read 책장 전체 조회 API Response 정보 ->
수정 전 wish 책장 전체 조회 API Swagger Response 정보 ->
수정 후 ->
> [FIX] 책장 전체 조회 API 누락 데이터 및 응답 데이터 구성 수정

- src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
- src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
- src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfResponseDTO.java
- src/main/java/com/core/book/api/bookshelf/repository/ReadBooksRepository.java
- src/main/java/com/core/book/api/bookshelf/repository/WishBooksRepository.java
- src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
- close #91 
- read/wish 책장 전체 조회 시 페이징 처리 기능을 구현하였습니다. (page 기본 값: 1, size 기본 값: 10)
- url 예시 : /api/v1/bookshelf/wish?member-id=1&page=1&size=10
- url 예시 : /api/v1/bookshelf/wish?member-id=1&page=1&size=10
- read 책장 전체 조회 Response Body 구성: 전체 정보 > 월별 정보 > 해당 월에 포함된 책 정보
&ensp;- 전체 정보 = 전체 책 개수 / 마지막 페이지 여부
&ensp;- 월별 정보 = 읽은 날짜(월별)(YYYY-M) / 월별 읽은 책 개수
&ensp;- 해당 월에 포함된 책 정보 = isbn / 책 이미지 / 평점 / 책 제목 / 읽은 날짜
read 책장 전체 조회(1) =>
read 책장 전체 조회(2) =>
wish 책장 전체 조회 =>
> [FEAT] 책장 전체 조회 페이징 처리 기능 구현

- src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
- src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfResponseDTO.java
- src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
- close #106 
- 책장 전체 조회 API 응답에 페이징 처리를 위한 page(현재 페이지 번호) 데이터를 추가하였습니다.
> [FIX] 책장 전체 조회 API 응답에 page 데이터 추가

- src/main/java/com/core/book/api/book/controller/BookController.java
- src/main/java/com/core/book/api/book/dto/BookInfoDTO.java
- src/main/java/com/core/book/api/book/service/BookService.java
- src/main/java/com/core/book/common/response/ErrorStatus.java
- src/main/java/com/core/book/common/response/SuccessStatus.java
- close #105 
- 책 정보 자세히보기 API 에서 단일 책 정보 가져오기 기능을 구현하였습니다.
- 책 정보는 (데이터가 있다면) DB에서 우선으로 가져오고, (없다면) 외부 도서 API를 호출해 정보를 가져옵니다.
> [FEAT] 책 정보 자세히보기 API 단일 책 정보 가져오기 기능 구현

- src/main/java/com/core/book/api/book/controller/BookController.java
- src/main/java/com/core/book/api/book/dto/BookDTO.java
- src/main/java/com/core/book/api/book/dto/BookInfoDTO.java
- src/main/java/com/core/book/api/book/dto/BookResponseDTO.java
- src/main/java/com/core/book/api/book/entity/Book.java
- src/main/java/com/core/book/api/book/service/BookService.java
- src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfRequestDTO.java
- src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfRequestDTO.java
- src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
- src/main/java/com/core/book/common/response/ErrorStatus.java
- src/main/java/com/core/book/common/response/SuccessStatus.java
- close #109 
- 기존 BookDTO를 사용하던 코드를 BookInfoDTO를 사용하도록 변경하였습니다.
- 이를 통해 BookDTO의 필요 없는 데이터(link, discount) 및 (책장 등록 API의) RequestBody에서 입력 받지 않아도 될 bookTag 데이터를 삭제하여 클라이언트 단에서 혼동될 요소를 제거합니다.
- 책 검색 API에서 반환되는 bookList 요소 중 'description(책 소개)'은 검색 페이지에서 사용되지 않는 데이터 입니다.
- 다만, 검색 페이지를 통해 책을 등록하는 로직이 수행될 경우 (e.g. 책장 등록 API) bookList의 모든 데이터를 사용합니다.
책 검색 API 반환 데이터 ->
책 정보 자세히 보기 API 반환 데이터 (현재 개발중, 추가 데이터 있음) ->
책장 등록 API Request Body (기존에 필요 없던 link, discount, bookTag 데이터 삭제함) ->
> [FIX] 기존 BookDTO 사용 코드 BookInfoDTO로 변경

- src/main/java/com/core/book/api/article/controller/ArticleViewController.java
- src/main/java/com/core/book/api/article/dto/ArticleListDTO.java
- src/main/java/com/core/book/api/article/dto/ArticleListResponseDTO.java
- src/main/java/com/core/book/api/article/dto/ReviewArticleListDTO.java
- src/main/java/com/core/book/api/article/dto/ReviewArticleListResponseDTO.java
- src/main/java/com/core/book/api/article/entity/Article.java
- src/main/java/com/core/book/api/article/entity/ReviewArticle.java
- src/main/java/com/core/book/api/article/repository/ArticleRepository.java
- src/main/java/com/core/book/api/article/repository/ReviewArticleRepository.java
- src/main/java/com/core/book/api/article/service/ArticleViewService.java
- src/main/java/com/core/book/common/entity/BaseTimeEntity.java
- close #99
- 기존 게시글 전체 불러오기 로직을 대폭 수정하여 조회타입이 ALL 인 경우 REVIEW, PHRASE, QNA 게시글 가장 최신순으로 불러옵니다.
- 응답시 page 번호와 해당 게시글의 타입도 반환되도록 수정하였습니다.
> [FIX] 게시글 전체보기 API 데이터 불러오기 로직 수정

- src/main/java/com/core/book/api/comment/controller/CommentController.java
- src/main/java/com/core/book/api/comment/dto/CommentCreateDTO.java
- src/main/java/com/core/book/api/comment/dto/CommentResponseDTO.java
- src/main/java/com/core/book/api/comment/dto/CommentUpdateDTO.java
- src/main/java/com/core/book/api/comment/entity/Comment.java
- src/main/java/com/core/book/api/comment/repository/CommentRepository.java
- src/main/java/com/core/book/api/comment/service/CommentService.java
- src/main/java/com/core/book/common/response/ErrorStatus.java
- src/main/java/com/core/book/common/response/SuccessStatus.java
- close #100
- 댓글 작성,조회,수정,삭제 API를 구현하였습니다.
- 댓글 삭제 기능 에서 자식댓글이 존재하고있을 때 부모댓글 삭제 시도시 어떻게 처리해야할지 의논해야합니다.
(댓글 작성)
(댓글 조회)
(댓글 수정)
(댓글 삭제)
> [FEAT] 댓글 등록, 조회, 수정, 삭제 기능 조회 구현

- src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
- src/main/java/com/core/book/api/bookshelf/dto/ReadBooksDTO.java
- src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
- src/main/java/com/core/book/api/bookshelf/dto/WishBooksDTO.java
- src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
- close #123 
- 책장 전체 조회 API 응답에 읽은 책의 id 값을 추가하였습니다. 이를 통해 프론트 단에서 id 값으로 상세 정보 조회 및 수정 시 사용할 수 있습니다.
- userId 코드 컨벤션 수정하였습니다. 기존 userId를 프론트 단에서 받는 로직에서 토큰 인증으로 인증 로직을 수정하였습니다.
userId 토큰 인증 로직 ->
> [FIX] 책장 전체 조회 API - 응답에 읽은 책의 id 값 추가하기 & userId 코드 컨벤션 수정

- src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
- src/main/java/com/core/book/api/bookshelf/dto/ReadBooksDTO.java
- src/main/java/com/core/book/api/bookshelf/dto/WishBooksDTO.java
- src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
- src/main/java/com/core/book/common/response/ErrorStatus.java
- close #125 
- 책장 상세 정보 수정 API 에 '책장 소유자와 수정 요청자가 다른 경우' 예외 처리를 구현하였습니다.
- 책장 삭제 API 에 '책장 소유자와 삭제 요청자가 다른 경우' 예외 처리를 구현하였습니다.
- 이전 userId 코드 컨벤션을 구현하다 책장 등록 시 memberId 를 저장하는 코드를 삭제하는 오류를 범하여 이를 수정하였습니다.
'책장 소유자와 수정 요청자가 다른 경우' 예외처리 ->
'책장 소유자와 삭제 요청자가 다른 경우' 예외처리 ->
> [FIX] 책장 수정/삭제 API - 타 사용자 수정/삭제 예외처리

- src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
- close #130 
- 읽은 책 책장 상세 정보 조회 API에서, 초기 책장(read) 등록 시 태그 저장이 안된 경우(NULL) 상세 정보 조회가 NULL로 조회되지 않고 오류가 나는 문제를 해결하였습니다.
- 읽은 책 책장 상세 정보 수정 API에서, 책 태그 수정만 반영이 안되는 오류를 해결하였습니다.
책 상세 정보 수정 - 태그 수정 성공 ->
책 태그가 없을 경우, 응답 출력 ->
> [FIX] 읽은 책 책장 API - 책 태그 수정 오류 및 NULL 저장 오류 해결

- src/main/java/com/core/book/api/member/controller/MemberController.java
- src/main/java/com/core/book/api/member/service/MemberService.java
- close #138
- 회원가입시 GUEST 에서 USER로 승격되는 시점을 변경하였습니다. (처음 카카오 로그인 시도 후 최종 닉네임 변경이 진행되어야 일반유저(Role.USER)로 전환)
- 프로필사진 변경, 닉네임 변경 컨트롤러 매핑을 수정하였습니다.
> [FIX] 회원가입 로직(닉네임 체크) 수정

- src/main/java/com/core/book/api/article/controller/ArticleController.java
- src/main/java/com/core/book/api/article/controller/ArticleCreateController.java
- src/main/java/com/core/book/api/article/controller/ArticleDeleteController.java
- src/main/java/com/core/book/api/article/controller/ArticleModifyController.java
- src/main/java/com/core/book/api/article/controller/ArticleViewController.java
- src/main/java/com/core/book/api/article/dto/QuotationArticleCreateDTO.java
- src/main/java/com/core/book/api/article/dto/QuotationArticleListResponseDTO.java
- src/main/java/com/core/book/api/article/dto/QuotationArticleModifyDTO.java
- src/main/java/com/core/book/api/article/dto/QuotationArticleResponseDTO.java
- src/main/java/com/core/book/api/article/entity/Article.java
- src/main/java/com/core/book/api/article/entity/PhraseArticle.java
- src/main/java/com/core/book/api/article/entity/QnaArticle.java
- src/main/java/com/core/book/api/article/entity/QuotationArticle.java
- src/main/java/com/core/book/api/article/entity/ReviewArticle.java
- src/main/java/com/core/book/api/article/repository/ArticleLikeRepository.java
- src/main/java/com/core/book/api/article/repository/QnaArticleContentRepository.java
- src/main/java/com/core/book/api/article/repository/QuotationArticleRepository.java
- src/main/java/com/core/book/api/article/service/ArticleCreateService.java
- src/main/java/com/core/book/api/article/service/ArticleDeleteService.java
- src/main/java/com/core/book/api/article/service/ArticleModifyService.java
- src/main/java/com/core/book/api/article/service/ArticleService.java
- src/main/java/com/core/book/api/article/service/ArticleViewService.java
- src/main/java/com/core/book/api/comment/repository/CommentRepository.java
- src/main/java/com/core/book/api/comment/service/CommentService.java
- src/main/java/com/core/book/common/response/ErrorStatus.java
- close #153
- 인용 게시글 등록,수정,삭제,조회 기능을 구현하였습니다.
- 각 게시글, 댓글 등등 현재 구현 단계에서는 하드삭제(즉시 삭제)로 구현되어있지만 추후 배포단계에서 법률적인 문제 등으로 인해 리팩토링 단계에서 소프트삭제(실질적인 삭제가 아닌 필드를 통한 논리적 삭제)로 변경해야합니다. 또한 추후 IP주소를 수집해야하는 로직도 추가해야합니다.
[ 게시글 등록 ]
[ 게시글 조회 ]
[ 게시글 수정 ]
[ 게시글 삭제 ]
> [FEAT] 인용 게시글 등록,수정,삭제,조회 기능 구현

- src/main/java/com/core/book/api/article/service/ArticleDeleteService.java
- src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
- close #158 
- 책장 삭제 시, 삭제되는 평점을 평균 평점에 반영하였습니다. 
- 감상평 게시글 삭제 시, 삭제되는 평점을 평균 평점에 반영하였습니다. 
- 평점 계산 메서드 코드 리팩토링 예정입니다
1. 게시글 생성 ->  평점 5.0 입력 -> 평균 평점 ((1.0+5.0+5.0+5.0)/4=4.0)
2. 게시글 삭제 -> 평점 5.0 삭제 -> 평균 평점 ((1.0+5.0+5.0)/3=3.66....)
> [FIX] 평점 삭제 시 평균 평점 갱신
