Dockerfile

- close #3 
CI/CD 전 Dockerfile 생성했습니다.

[SETTING] Dockerfile 생성

---

build.gradle
src/main/java/com/core/book/BookApplication.java
src/main/java/com/core/book/api/HealthCheckController.java
src/main/java/com/core/book/common/advice/ControllerExceptionAdvice.java
src/main/java/com/core/book/common/entity/BaseTimeEntity.java
src/main/java/com/core/book/common/exception/BaseException.java
src/main/java/com/core/book/common/response/ApiResponse.java
src/main/java/com/core/book/common/response/ErrorStatus.java
src/main/java/com/core/book/common/response/SuccessStatus.java

- close #5
프로젝트 파일 기본 세팅하였습니다.

[SETTING] 프로젝트 파일 등록

---

src/main/java/com/core/book/api/HealthCheckController.java

- close #7 
health check API 를 구현하였습니다.

[FEAT] health Check API 구현

---

build.gradle

- close #9
JPA 활성화 하기 위해 H2를 임의로 설정하였습니다.

[FIX] JPA H2 임의 설정

---

build.gradle

- close #12
build.gradle H2 -> Mysql 로 변경했습니다.

[SETTING] H2 -> Mysql 로 변경

---

build.gradle
src/main/java/com/core/book/api/member/controller/MemberController.java
src/main/java/com/core/book/api/member/entity/Member.java
src/main/java/com/core/book/api/member/entity/Role.java
src/main/java/com/core/book/api/member/jwt/filter/JwtAuthenticationProcessingFilter.java
src/main/java/com/core/book/api/member/jwt/service/JwtService.java
src/main/java/com/core/book/api/member/jwt/util/PasswordUtil.java
src/main/java/com/core/book/api/member/oauth2/CustomOAuth2User.java
src/main/java/com/core/book/api/member/oauth2/OAuthAttributes.java
src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginFailureHandler.java
src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java
src/main/java/com/core/book/api/member/oauth2/userinfo/KakaoOAuth2UserInfo.java
src/main/java/com/core/book/api/member/oauth2/userinfo/OAuth2UserInfo.java
src/main/java/com/core/book/api/member/repository/MemberRepository.java
src/main/java/com/core/book/api/member/service/MemberService.java
src/main/java/com/core/book/common/config/SecurityConfig.java
src/main/java/com/core/book/common/config/jwt/JwtConfig.java
src/main/java/com/core/book/common/config/oauth2/OAuth2Config.java
src/main/java/com/core/book/common/config/swagger/SwaggerConfig.java
src/main/java/com/core/book/common/exception/NotFoundException.java
src/main/java/com/core/book/common/response/ErrorStatus.java
src/main/java/com/core/book/common/response/SuccessStatus.java

- close #16 
Front-End 와 협업을 위한 Swagger 기반 API 명세서 기능을 적용하였습니다.

[FEAT] Swagger - API 명세서 기능 적용

---

src/main/java/com/core/book/api/book/controller/BookController.java
src/main/java/com/core/book/api/book/dto/BookDto.java
src/main/java/com/core/book/api/book/dto/ResultDto.java
src/main/java/com/core/book/api/book/entity/Book.java
src/main/java/com/core/book/api/book/repository/BookRepository.java
src/main/java/com/core/book/api/book/service/BookService.java
src/main/java/com/core/book/common/response/SuccessStatus.java

- close #14 
네이버 도서 API 를 활용해 도서 데이터 요청 및 저장 기능을 구현했습니다.
- 도서 데이터 요청(검색) 및 저장 기능 엔드포인트 : {URL}/api/v1/book
- 네이버 도서 API는 '카테고리' 정보를 일체 반환하지 않습니다.
- 검색 시 일부 도서의 외국어 정보를 걸러내는 방법을 찾아야 할 것 같습니다.
- Q. BookController.java 파일에 ApiResponse 를 통한 응답 요청 반환 코드 부분에 ApiResponse 클래스가 제네릭 타입을 사용하지 않았다는 경고 메시지가 출력됩니다.

[FEAT] 도서 API 데이터 요청 및 저장 기능 구현

---

src/main/java/com/core/book/api/book/controller/BookController.java

- close #21 
- Response 관련 에러를 해결하였습니다.

[FIX] 도서 API Response 에러 해결

---

src/main/java/com/core/book/common/config/SecurityConfig.java

- close #23
스프링시큐리티 CORS 오류 해결 및 도메인 등록했습니다.

[FIX] 스프링시큐리티 CORS 오류 해결 및 도메인 등록

---

src/main/java/com/core/book/common/config/SecurityConfig.java

- close #25
스프링시큐리티 책 검색 API 토큰인증 해제합니다.

[FIX] 스프링시큐리티 책 검색 API 토큰인증 해제

---

src/main/java/com/core/book/common/config/swagger/SwaggerConfig.java

- close #27
SwaggerConfig 에서 Base Server URL을 https로 변경했습니다.

[FIX] SwaggerConfig 에서 Base Server URL을 https로 변경

---

src/main/java/com/core/book/api/HealthCheckController.java
src/main/java/com/core/book/common/config/swagger/SwaggerConfig.java

- close #29 
- Swagger 쿠키 인증 기능 구현 및 https 적용했습니다.
- HealthCheck API Swagger TAG 설정하였습니다.

[FIX] Swagger 쿠키 인증 기능 구현 및 https 적용

---

src/main/java/com/core/book/api/book/controller/BookController.java

- close #32 
도서 API 기능 내 잘못 기재된 Swagger 설명을 수정하였습니다.

[FIX] 도서 API Swagger 설명 수정

---

src/main/java/com/core/book/api/book/controller/BookController.java
src/main/java/com/core/book/api/book/dto/BookDto.java
src/main/java/com/core/book/api/book/entity/Book.java
src/main/java/com/core/book/api/book/entity/BookTag.java
src/main/java/com/core/book/api/book/service/BookService.java
src/main/java/com/core/book/api/member/controller/MemberController.java
src/main/java/com/core/book/common/response/ApiResponse.java
src/main/java/com/core/book/common/response/ErrorStatus.java

- close #37 
책 태그를 담는 BookTag 엔티티를 생성하였습니다.
Book 엔티티가 관계의 주인인 일대일 단방향 관계로 설정하였습니다.

[FIX] 책 태그 entity 추가

---

build.gradle
src/main/java/com/core/book/api/member/controller/MemberController.java
src/main/java/com/core/book/api/member/dto/FollowRequestDTO.java
src/main/java/com/core/book/api/member/dto/FollowedUserDTO.java
src/main/java/com/core/book/api/member/dto/InfoOpenRequestDTO.java
src/main/java/com/core/book/api/member/dto/UserInfoResponseDTO.java
src/main/java/com/core/book/api/member/entity/Follow.java
src/main/java/com/core/book/api/member/entity/InfoOpen.java
src/main/java/com/core/book/api/member/entity/Member.java
src/main/java/com/core/book/api/member/jwt/service/JwtService.java
src/main/java/com/core/book/api/member/repository/FollowRepository.java
src/main/java/com/core/book/api/member/repository/InfoOpenRepository.java
src/main/java/com/core/book/api/member/repository/MemberRepository.java
src/main/java/com/core/book/api/member/service/MemberService.java
src/main/java/com/core/book/api/member/service/S3Service.java
src/main/java/com/core/book/common/config/aws/S3Config.java
src/main/java/com/core/book/common/exception/InternalServerException.java
src/main/java/com/core/book/common/response/ErrorStatus.java
src/main/java/com/core/book/common/response/SuccessStatus.java

- close #36
- 회원 팔로우 기능과 팔로우한 사용자 목록 조회하는 기능을 구현하였습니다.
- 회원 정보 불러오기 API에서 팔로우 수를 반환하도록 수정하였습니다.

[FEAT] 회원 팔로잉 기능 구현

---

README.md

- close #56 
- 깃허브 리드미에 시스템 아키텍쳐 구조 초안을 등록하였습니다.

[FIX] 아키텍처 구조 초안 생성

---

build.gradle
src/main/java/com/core/book/BookApplication.java
src/main/java/com/core/book/api/member/controller/MemberController.java
src/main/java/com/core/book/api/member/dto/FollowerUserDTO.java
src/main/java/com/core/book/api/member/dto/OtherUserInfoResponseDTO.java
src/main/java/com/core/book/api/member/dto/UserInfoResponseDTO.java
src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java
src/main/java/com/core/book/api/member/service/MemberService.java
src/main/java/com/core/book/common/config/redis/CacheConfig.java
src/main/java/com/core/book/common/config/redis/RedisConfig.java
src/main/java/com/core/book/common/exception/UnauthorizedException.java
src/main/java/com/core/book/common/response/ErrorStatus.java
src/main/java/com/core/book/common/response/SuccessStatus.java

- close #59 
- 로그인 성공 후 처음사용자, 기존 사용자 리다이렉트 URL을 수정했습니다.

[FIX] 로그인 성공 리다이렉트 URL 수정

---

src/main/java/com/core/book/api/member/controller/MemberController.java
src/main/java/com/core/book/api/member/dto/OtherUserInfoResponseDTO.java
src/main/java/com/core/book/api/member/service/MemberService.java
src/main/java/com/core/book/common/exception/UnauthorizedException.java
src/main/java/com/core/book/common/response/ErrorStatus.java

- close #45
- 다른 사용자 정보 불러오는 기능을 구현하였습니다.

[FEAT] 다른 사용자 정보 불러오는 기능 구현

---

build.gradle
src/main/java/com/core/book/BookApplication.java
src/main/java/com/core/book/api/member/controller/MemberController.java
src/main/java/com/core/book/api/member/dto/FollowerUserDTO.java
src/main/java/com/core/book/api/member/dto/OtherUserInfoResponseDTO.java
src/main/java/com/core/book/api/member/dto/UserInfoResponseDTO.java
src/main/java/com/core/book/api/member/service/MemberService.java
src/main/java/com/core/book/common/config/redis/CacheConfig.java
src/main/java/com/core/book/common/config/redis/RedisConfig.java
src/main/java/com/core/book/common/exception/UnauthorizedException.java
src/main/java/com/core/book/common/response/ErrorStatus.java
src/main/java/com/core/book/common/response/SuccessStatus.java

- close #53 
- 팔로워 사용자 목록 조회 API를 구현하였습니다.
- 팔로우 관련 기능 DB 쿼리 최적화를 위해 Redis를 활용한 캐싱 전략을 구성하였습니다 (DB 캐시 유효시간 5분)
- 캐시 키 일관성을 위해 서비스 단에서 사용자 구별 값을 userId로 통일하였습니다.
- MemberController에서 불필요한 주석을 삭제하였습니다.
- 사용자 정보 조회, 타인 사용자 정보 조회 API에서 팔로워수를 반환하는 필드를 추가하였습니다.
Redis 란? : https://wildeveloperetrain.tistory.com/21
(사용자 정보 조회 API)
(타인 사용자 정보 조회 API)
(팔로워 정보 조회 API)

[FIX] 팔로잉 기능 최적화 및 팔로워 보기 기능 구현

---

src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java

- close #61
- 로그인 성공 리다이렉트 URL 포트를 3000 에서 8100으로 변경하였습니다.

[FIX] 로그인 성공 리다이렉트 URL 포트 수정

---

src/main/java/com/core/book/api/member/jwt/filter/JwtAuthenticationProcessingFilter.java
src/main/java/com/core/book/api/member/jwt/service/JwtService.java
src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java
src/main/java/com/core/book/api/member/service/MemberService.java

- close #63
- 로그인 진행시 테스트 도메인(localhost) 이름으로 된 JWT 토큰 쿠키를 생성하도록 로직 수정하였습니다.

[FIX] 테스트 도메인 JWT 토큰 생성 로직 수정

---

src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java

- close #65
- JWT 토큰 전달을 쿠키에서 JSON 응답 형식으로 변경했습니다.

[FIX] JWT 토큰 전달 방식 변경

---

src/main/java/com/core/book/api/member/controller/MemberController.java
src/main/java/com/core/book/api/member/dto/InfoOpenRequestDTO.java
src/main/java/com/core/book/api/member/dto/UserInfoResponseDTO.java
src/main/java/com/core/book/api/member/entity/InfoOpen.java
src/main/java/com/core/book/api/member/service/MemberService.java
src/main/java/com/core/book/common/config/swagger/SwaggerConfig.java

- close #69
- 스웨거 누락 정보 추가 및 수정, 정보공개 필드를 카멜케이스로 변경하였습니다.

[FIX] 스웨거 누락 정보 추가 및 수정, 정보공개 필드 카멜케이스 변경

---

src/main/java/com/core/book/api/member/dto/FollowedUserDTO.java
src/main/java/com/core/book/api/member/dto/FollowerUserDTO.java
src/main/java/com/core/book/api/member/repository/FollowRepository.java
src/main/java/com/core/book/api/member/service/MemberService.java

- close #71
- 팔로워 조회 API 에서 상대방 팔로우 여부를 보여주는 기능을 구현하였습니다.

[FIX] 팔로워 중 해당 유저 팔로잉 여부 체크 기능 구현

---

src/main/java/com/core/book/common/config/SecurityConfig.java

- close #79 
- 토큰 재발급 시 프론트에서 안보이는 문제를 해결하기위해 스프링시큐리티 CORS ExposedHeader 설정을 추가하였습니다.

[FIX] 스프링시큐리티 CORS ExposedHeader 설정

---

src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
src/main/java/com/core/book/api/bookshelf/dto/ReadBooksDTO.java
src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfRequestDTO.java
src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfRequestDTO.java
src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java

- close #84 
- Bookshelf API 내 몇몇 API의 Response Body에 DTO가 붙어있는 Key 이름을 전부 수정하였습니다. 그 과정에서 변경된 변수 이름에 따른 Service 코드도 일부 수정하였습니다.

[FIX] Bookshelf API Response Body 의 Key(키/필드) 이름 수정

---

src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java

- close #86 
- close #84 PR의 Merge 실패를 처리하고자 Bookshelf Service 코드 내 DTO 변수 이름을 수정하였습니다.

[FIX] Bookshelf Service 코드 내 DTO 변수 이름 수정

---

src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
src/main/java/com/core/book/api/bookshelf/dto/ReadBooksDTO.java
src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfResponseDTO.java
src/main/java/com/core/book/api/bookshelf/entity/ReadBooks.java
src/main/java/com/core/book/api/bookshelf/repository/ReadBooksRepository.java
src/main/java/com/core/book/api/bookshelf/repository/WishBooksRepository.java
src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java

- close #77 
책장 필터 (전체보기(default, 최신순)/오래된 순/평점 높은 순/평점 낮은 순) 기능을 구현하였습니다.
- 전체 조회 API 에서 원하는 필터의 종류 번호를 `@RequestParam(value = "filter", defaultValue = "1") int filterNum` 을 통해 받을 수 있게 구현하였습니다.
- 필터 종류 번호 -> 1: 전체보기(최신순), 2: 오래된 순, 3: 평점 높은 순, 4: 평점 낮은 순
전체보기(default, 최신순) (filterNum = 1) =>
오래된 순 (filterNum = 2) =>
평점 높은 순 (filterNum = 3) =>
평점 낮은 순 (filterNum = 4) =>

[FEAT] 책장 필터 기능 구현

---

src/main/java/com/core/book/api/bookshelf/repository/ReadBooksRepository.java
src/main/java/com/core/book/api/bookshelf/repository/WishBooksRepository.java

[FIX] 책장 코드 충돌 문제 해결

---

src/main/java/com/core/book/api/article/service/ArticleViewService.java
src/main/java/com/core/book/api/book/controller/BookController.java
src/main/java/com/core/book/api/book/dto/ResultDTO.java
src/main/java/com/core/book/api/book/entity/Book.java
src/main/java/com/core/book/api/book/service/BookService.java
src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java

- close #98 
- 도서 API 요청 검색 결과 JSON에서 XML 형식으로 수정하였습니다.
- Map 으로 반환하던 검색 결과를 DTO 형식으로 변환하면서 검색 페이지에서 필요 없는 데이터 응답을 제거하였습니다.
- 검색 결과 페이징 처리를 위해 응답 데이터에 page(현재 페이지 번호)와 isLast(마지막 페이지 여부) 변수를 추가하였습니다.

[FIX] 도서 API 요청 결과 XML 형식으로 수정 및 응답 형식 수정

---

build.gradle

- close #98 
- build.gradle 파일에 Jackson XML 데이터 형식 라이브러리를 추가하였습니다.

[FIX] build.gradle 에 Jackson XML 데이터 형식 라이브러리 추가

---

src/main/java/com/core/book/api/book/dto/BookDTO.java
src/main/java/com/core/book/api/book/dto/BookResponseDTO.java
src/main/java/com/core/book/api/book/dto/ChannelDTO.java

- close #98 
- 누락된 DTO 파일을 업로드합니다.

[FIX] 누락된 DTO 파일로 인한 BOOK 코드 충돌 문제 해결

---

src/main/java/com/core/book/api/article/entity/Article.java
src/main/java/com/core/book/api/article/entity/ReviewArticle.java
src/main/java/com/core/book/api/article/repository/ArticleRepository.java
src/main/java/com/core/book/common/entity/BaseTimeEntity.java

- close #112 
- 여러 게시글을 관리하기 위해 게시글 엔티티를 추상클래스로 변환하였습니다.
- 해당 추상 클래스를 개발하고있는 댓글 관련 기능에 적용 할 예정입니다.

[FIX] 게시글 엔티티 추상클래스 변환

---

src/main/java/com/core/book/api/article/entity/Article.java
src/main/java/com/core/book/api/article/entity/ReviewArticle.java
src/main/java/com/core/book/api/comment/service/CommentService.java

- close #116
-  댓글 등록, 삭제 시 해당 게시물의 댓글 수 카운트를 조절하는 기능을 구현하였습니다.

[FIX] 게시글 댓글 수 등록 로직 수정 

---

src/main/java/com/core/book/common/entity/BaseTimeEntity.java

- close #119
-BaseTimeEntity 중복 SuperBuild 어노테이션을 제거하였습니다.

[FIX] BaseTimeEntity 중복 SuperBuild 어노테이션 제거

---

src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfResponseDTO.java
src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java

- close #128 
읽고 싶은 책 책장 전체 조회 API의 응답에 읽고 싶은 책의 id 값을 추가하였습니다.

[FIX] 읽고 싶은 책 책장 전체 조회 API - 응답에 읽고 싶은 책의 id 값 추가하기

---

src/main/java/com/core/book/api/article/dto/ReviewArticleCreateDTO.java
src/main/java/com/core/book/api/article/dto/ReviewArticleDetailDTO.java
src/main/java/com/core/book/api/article/entity/ReviewArticle.java
src/main/java/com/core/book/api/article/service/ArticleCreateService.java
src/main/java/com/core/book/api/article/service/ArticleModifyService.java
src/main/java/com/core/book/api/article/service/ArticleViewService.java
src/main/java/com/core/book/api/book/entity/Book.java
src/main/java/com/core/book/api/bookshelf/dto/ReadBooksDTO.java
src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
src/main/java/com/core/book/api/bookshelf/entity/ReadBooks.java
src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java

- close #121 
- REVIEW_ARTICLE, READBOOKS 의 속성 이름 star_rating -> rating 으로 변경하였습니다.
- BOOK TABLE 'rating_average', 'rating_count' attribute를 추가하였습니다.
- 새로운 평점 입력 시(책장 평점 입력/수정 시, 감상평 게시글 평점 수정 시), 평균 평점 계산 기능 구현하였습니다.
- 이 과정에서 평점 '수정'의 경우 기존 평균 평점에서 rating_count 를 늘리지 않고, 이전 평점에서 대체된 평점으로 평균이 계산되도록 올바른 로직을 구현하였습니다. 
- 평균 평점은 소수점 둘째 자리까지 표시됩니다.

[FEAT] 책 정보 자세히보기 API - 전체 평점 기능 구현

---

src/main/java/com/core/book/api/article/controller/ArticleCreateController.java
src/main/java/com/core/book/api/article/controller/ArticleDeleteController.java
src/main/java/com/core/book/api/article/controller/ArticleModifyController.java
src/main/java/com/core/book/api/article/controller/ArticleViewController.java
src/main/java/com/core/book/api/article/dto/PhraseArticleContentDTO.java
src/main/java/com/core/book/api/article/dto/PhraseArticleContentDetailDTO.java
src/main/java/com/core/book/api/article/dto/PhraseArticleCreateDTO.java
src/main/java/com/core/book/api/article/dto/PhraseArticleDetailDTO.java
src/main/java/com/core/book/api/article/entity/PhraseArticle.java
src/main/java/com/core/book/api/article/entity/PhraseArticleContent.java
src/main/java/com/core/book/api/article/repository/PhraseArticleContentRepository.java
src/main/java/com/core/book/api/article/repository/PhraseArticleRepository.java
src/main/java/com/core/book/api/article/service/ArticleCreateService.java
src/main/java/com/core/book/api/article/service/ArticleDeleteService.java
src/main/java/com/core/book/api/article/service/ArticleModifyService.java
src/main/java/com/core/book/api/article/service/ArticleViewService.java

- close #122 
- 인상깊은구절 등록/조회/수정/삭제 기능을 구현했습니다.
[인상깊은구절 게시글 등록]
[인상깊은구절 게시글 조회]
[인상깊은구절 게시글 수정]
[인상깊은구절 게시글 삭제]

[FEAT] 인상깊은구절 게시판 등록/조회/수정/삭제 기능 구현

---

src/main/java/com/core/book/api/article/controller/ArticleCreateController.java
src/main/java/com/core/book/api/article/service/ArticleCreateService.java
src/main/java/com/core/book/api/bookshelf/repository/ReadBooksRepository.java
src/main/java/com/core/book/common/response/SuccessStatus.java

- close #150 
- 읽은 책 책장에서 isbn 을 검색해 해당 사용자의 책장에 책이 있는지 유무를 판단합니다.
- 책장에 있다면 "hasReadBook" : true / 책장에 없다면 "hasReadBook" : false
- 추가로, 책장에 있는 경우 "readBookId" : {id} 로 책장 id 값이 반환됩니다. 해당 id 값으로 평가정보를 불러와 주세요! (프론트 역할)

[FEAT] 읽은 책 책장 내 책 존재 유뮤 확인 API 구현

---

src/main/java/com/core/book/api/article/repository/ArticleRepository.java
src/main/java/com/core/book/api/article/service/ArticleCreateService.java
src/main/java/com/core/book/api/article/service/ArticleModifyService.java
src/main/java/com/core/book/api/book/controller/BookController.java
src/main/java/com/core/book/api/book/dto/BookInfoDetailDTO.java
src/main/java/com/core/book/api/book/dto/ReviewPreviewDTO.java
src/main/java/com/core/book/api/book/entity/Book.java
src/main/java/com/core/book/api/book/repository/UserBookTagRepository.java
src/main/java/com/core/book/api/book/service/BookService.java
src/main/java/com/core/book/api/book/service/UserBookTagService.java
src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java

- close #134
- 책에 달린 Best 5 태그 계산 기능을 구현하였습니다.
- 책 정보 자세히보기 API의 평가정보(평점(평균), Best5 태그, 리뷰 미리보기) 를 반환하였습니다.

[FEAT] 책 정보 자세히보기 API - 평가정보(평점(평균), Best5 태그, 리뷰 미리보기) 반환

---

build.gradle
src/main/java/com/core/book/BookApplication.java
src/main/java/com/core/book/api/member/service/MemberService.java
src/main/java/com/core/book/common/config/redis/CacheConfig.java
src/main/java/com/core/book/common/config/redis/RedisConfig.java

- close #161
- Redis 서버 이전을 위해 멤버 캐싱 전략을 해제합니다.
- 해제를 위해 관련 Redis Config, Cache Config를 주석화 하였습니다.

[REFAC] Redis 캐싱 임시 해제

---

.github/workflows/gradle.yml

- close #164
- 기존에 구축된 dev -> 바로 배포 CI/CD 전략을 dev -> main(QA, 최종 테스트가 완료된 코드) 브랜치(CI)로 Push 될 시 CD(메인 백엔드 서버) 작동되도록 수정하였습니다.

[FIX] CICD 파이프라인 업데이트

---

.github/workflows/gradle.yml
src/main/java/com/core/book/common/config/SecurityConfig.java

- close #169 
- 스프링시큐리티에 새로운 프론트엔드 CORS URL을 등록하였습니다.

[REFAC] 스프링시큐리티 CORS URL 변경
